In [550]:
import numpy as np

In [551]:
# стандартный python
a = list(range(1000000))

In [552]:
%%timeit

[e*e for e in a]

37.3 ms ± 837 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [553]:
# библиотека numpy
a = np.arange(1000000)

In [554]:
%%timeit

a*a

487 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [555]:
# стандартный python
rows, cols = 1000, 1000

a = [list(range(i, i + cols)) for i in range (0, rows)]
b = [[0 for j in range(cols)] for i in range(rows)]

In [556]:
%%timeit

for i in range(rows):
    for j in range(cols):
        b[i][j] = 2*a[i][j]

63.8 ms ± 4.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [557]:
# библиотека numpy
a = np.asarray(a)

In [558]:
%%timeit

2*a

499 µs ± 39.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [559]:
# целочисленный массив
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [560]:
# массив из чисел с плав. точкой
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [561]:
# двумерный массив
a = np.array([[1, 2, 3, 4, 5], 
             [6, 7, 8, 9, 0]], dtype=float)
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [562]:
# его размерность
a.shape

(2, 5)

In [563]:
# количество размерностей
a.ndim

2

In [564]:
# тип данных массива
a.dtype

dtype('float64')

In [565]:
# приводим его к int
a.astype(int)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [566]:
# размер одной строки и одного элемента массива
a.strides

(40, 8)

In [567]:
# изменим форму массива
b = a.reshape(5, 2)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [568]:
# размер одной строки и одного элемента нового массива
b.strides

(16, 8)

In [569]:
# два массива ссылаются на одну и ту же область памяти
a[0, 1] = -10
b

array([[  1., -10.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.],
       [  9.,   0.]])

In [570]:
# стягиваем в одну строку (новый массив)
b = a.flatten()
a[0, 1] = -30

b

array([  1., -10.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [571]:
# стягиваем в одну строку (тот же массив)
b = a.ravel()
a[0, 1] = -20

b

array([  1., -20.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [572]:
# транспонирование (тот же массив)
c = a.T
a[0, 1] = -40

c

array([[  1.,   6.],
       [-40.,   7.],
       [  3.,   8.],
       [  4.,   9.],
       [  5.,   0.]])

In [573]:
# такое возможно благодаря изменению strides
c.strides, a.strides

((8, 40), (40, 8))

In [574]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [575]:
# фиктивная ось
b[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [576]:
# вектор-столбец
b[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [577]:
# добавление нескольких фиктивных осей
b[np.newaxis, :, np.newaxis].shape

(1, 10, 1)

In [578]:
# массив из нулей
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [579]:
# массив из нулей размерности
# существующего массива
np.zeros_like(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [580]:
# массив единиц
np.ones(5)

array([1., 1., 1., 1., 1.])

In [581]:
# единичная матрица
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [582]:
# различные способы ранжирования
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [583]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [584]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [585]:
# разбивание диапазона на 4 равных отрезка
np.linspace(0, 1, 5, endpoint=True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [586]:
# избегаем ненужного копирования
a = np.array([1, 2, 3, 4, 5])
b = np.asarray(a)
c = np.array(a)

a[0] = 0

b, c

(array([0, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [587]:
# другой тип с помощью asarray
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
b = np.asarray(a, dtype=np.int32)
c = np.array(a)

a, b, c

(array([1., 2., 3., 4., 5.], dtype=float32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [588]:
# при этом уже будет создана копия
a[0] = 0
a, b, c

(array([0., 2., 3., 4., 5.], dtype=float32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [589]:
# массив из списка (снова копия)
d = [1, 2, 3, 4 ,5]
a = np.asarray(d)

d[0] = 0
a

array([1, 2, 3, 4, 5])

In [590]:
# ОПЕРАЦИИ СО СКАЛЯРАМИ И УНАРНЫЕ ОПЕРАЦИИ

In [591]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [592]:
a**3 # или np.power(a, 3)

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])

In [593]:
a+2 # или np.add(a, 2)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [594]:
a*2 # или np.multiply(a, 2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [595]:
2*a # или np.multiply(2, a)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [596]:
2**a # или np.power(2, a)

array([[  1,   2,   4,   8,  16],
       [ 32,  64, 128, 256, 512]])

In [597]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [598]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [599]:
np.log(1+a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [600]:
np.log2(1+a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [601]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [602]:
a>0 # или np.greater(a, 0)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [603]:
# АГРЕГИРУЮЩИЕ ОПЕРАЦИИ

In [604]:
np.random.seed(5656)
a=np.random.randint(0, 10, size=(7, ))
a[3] = 10
a

array([ 4,  6,  7, 10,  0,  3,  5])

In [605]:
a.min(), a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(0, 10, 3, 35, 0, 5.0)

In [606]:
np.min(a), np.max(a), np.argmax(a), np.sum(a), np.prod(a), np.mean(a)

(0, 10, 3, 35, 0, 5.0)

In [607]:
np.random.seed(5555)
a=np.random.randint(0, 10, size=(3, 7))
a[1, 3] = 15
a

array([[ 2,  3,  0,  5,  2,  0,  3],
       [ 8,  8,  0, 15,  1,  5,  3],
       [ 0,  1,  6,  2,  1,  4,  5]])

In [608]:
# максимумы по столбцам
a.max(axis=0)

array([ 8,  8,  6, 15,  2,  5,  5])

In [609]:
# сумма по строкам
a.sum(axis=1)

array([15, 40, 19])

In [610]:
a.argmax()

10

In [611]:
a.ravel()[a.argmax()]

15

In [612]:
i = np.argmax(a)
i, j = i // a.shape[1], i % a.shape[1]
print("index =", (i, j))

index = (1, 3)


In [613]:
b = np.random.randint(0, 10, size=(1000, 1000))
b[36, 42] = 20
b = b.ravel()

In [614]:
%%timeit

# numpy
b.max()

116 µs ± 6.65 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [615]:
%%timeit

# python
max(b)

33.1 ms ± 696 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [616]:
# УНАРНЫЕ ОПЕРАЦИИ НАД БУЛЕВЫМИ МАССИВАМИ

In [617]:
a = np.asarray([True, False, True, False, True])
a

array([ True, False,  True, False,  True])

In [618]:
a.any(), np.any(a), any(a)

(True, True, True)

In [619]:
a.all(), np.all(a), all(a)

(False, False, False)

In [620]:
a = np.asarray([[True, False, True, False, True],
                [False, True, False, True, False]])
a

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [621]:
a.any(axis=0)

array([ True,  True,  True,  True,  True])

In [622]:
a.all(axis=1)

array([False, False])

In [623]:
np.logical_not(a)

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [624]:
# БИНАРНЫЕ ОПЕРАЦИИ

In [625]:
a = a.astype(int)
a

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [626]:
np.random.seed(4968)
b = np.random.randint(0, 10, size=a.shape)
b

array([[3, 0, 8, 1, 3],
       [1, 0, 2, 7, 8]])

In [627]:
a*b # или np.multiply(a, b)

array([[3, 0, 8, 0, 3],
       [0, 0, 0, 7, 0]])

In [628]:
a+b # или np.add(a, b)

array([[4, 0, 9, 1, 4],
       [1, 1, 2, 8, 8]])

In [629]:
np.fmax(a, b)

array([[3, 0, 8, 1, 3],
       [1, 1, 2, 7, 8]])

In [630]:
a>b # или np.greater(a, b)

array([[False, False, False, False, False],
       [False,  True, False, False, False]])

In [631]:
np.random.seed(4987)
a = np.random.random(size=(2, 5))
b = a + np.random.random(size=(2, 5))*1e-5

In [632]:
a

array([[0.71700122, 0.2663399 , 0.363807  , 0.21265099, 0.97651262],
       [0.61392251, 0.62911827, 0.19253836, 0.96386783, 0.50772562]])

In [633]:
b

array([[0.71700756, 0.2663407 , 0.36381509, 0.21265902, 0.97651597],
       [0.61392769, 0.62912558, 0.19254206, 0.96387406, 0.50773147]])

In [634]:
np.isclose(a, b)

array([[ True,  True, False, False,  True],
       [ True, False, False,  True, False]])

In [635]:
np.allclose(a, b)

False

In [636]:
np.isclose(a, b).any()

True

In [637]:
np.random.seed(4987)
a = (np.random.random(size=(5, )) - 0.5) * 1e-7
np.isclose(a, 0, atol=1e-6)

array([ True,  True,  True,  True,  True])

In [638]:
# БИНАРНЫЕ ОПЕРАЦИИ НАД БУЛЕВЫМИ МАССИВАМИ

In [639]:
a = np.asarray([ True,  True, False, False,  True])
b = np.asarray([ True, False, False,  True, False])
a, b

(array([ True,  True, False, False,  True]),
 array([ True, False, False,  True, False]))

In [640]:
np.logical_and(a, b), np.logical_or(a, b), np.logical_xor(a, b)

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [641]:
a & b, a | b, a ^ b

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [642]:
np.bitwise_and(a, b), np.bitwise_or(a, b), np.bitwise_xor(a, b)

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [643]:
# сложение массивов разных размеров

a = np.arange(30).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [644]:
b = np.arange(a.shape[1])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [645]:
print("a.shape =", a.shape)
print("b.shape =", b.shape)

a.shape = (3, 10)
b.shape = (10,)


In [646]:
a+b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [647]:
b = np.arange(a.shape[0])
b

array([0, 1, 2])

In [648]:
print("a.shape =", a.shape)
print("b.shape =", b.shape)

a.shape = (3, 10)
b.shape = (3,)


In [650]:
# не получится

a+b

ValueError: operands could not be broadcast together with shapes (3,10) (3,) 

In [651]:
b = np.arange(a.shape[0])[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [652]:
print("a.shape =", a.shape)
print("b.shape =", b.shape)

a.shape = (3, 10)
b.shape = (3, 1)


In [653]:
a+b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [654]:
a = np.arange(5).reshape(1, -1)
a

array([[0, 1, 2, 3, 4]])

In [655]:
b = a.reshape(-1, 1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [656]:
print("a.shape =", a.shape)
print("b.shape =", b.shape)

a.shape = (1, 5)
b.shape = (5, 1)


In [657]:
a+b

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [658]:
a>=b

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False,  True]])

In [659]:
a = np.arange(20).reshape(4, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [660]:
np.random.seed(1987)

b = np.random.randint(-1, 2, size=(4, 5))
b

array([[-1,  1,  1,  1,  1],
       [ 1, -1, -1,  0,  0],
       [ 0,  1,  0,  1, -1],
       [-1,  0, -1, -1,  0]])

In [661]:
a*b

array([[  0,   1,   2,   3,   4],
       [  5,  -6,  -7,   0,   0],
       [  0,  11,   0,  13, -14],
       [-15,   0, -17, -18,   0]])

In [662]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [663]:
np.random.seed(7892)

b = np.random.randint(-1, 2, size=(4, 1))
b

array([[-1],
       [ 1],
       [ 1],
       [ 0]])

In [664]:
print("a.shape =", a.shape)
print("b.shape =", b.shape)

a.shape = (4, 5)
b.shape = (4, 1)


In [665]:
a*b # здесь столбец b повторился 5 раз, чтобы получить ту же размерность

array([[ 0, -1, -2, -3, -4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0]])

In [666]:
c = np.repeat(b, a.shape[1], axis=1)
c

array([[-1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0]])

In [667]:
print("a.shape =", a.shape)
print("c.shape =", c.shape)

a.shape = (4, 5)
c.shape = (4, 5)


In [668]:
a*c # результат тот же

array([[ 0, -1, -2, -3, -4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0]])

In [669]:
a = np.arange(20).reshape(-1, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [670]:
np.random.seed(6579)

b = np.random.randint(0, 2, size=5)
b

array([0, 0, 1, 1, 0])

In [671]:
print("a.shape =", a.shape)
print("b.shape =", b.shape)

a.shape = (4, 5)
b.shape = (5,)


In [672]:
a*b

array([[ 0,  0,  2,  3,  0],
       [ 0,  0,  7,  8,  0],
       [ 0,  0, 12, 13,  0],
       [ 0,  0, 17, 18,  0]])

In [673]:
c = b[np.newaxis, :]
c

array([[0, 0, 1, 1, 0]])

In [674]:
print("a.shape =", a.shape)
print("c.shape =", c.shape)

a.shape = (4, 5)
c.shape = (1, 5)


In [675]:
c*a

array([[ 0,  0,  2,  3,  0],
       [ 0,  0,  7,  8,  0],
       [ 0,  0, 12, 13,  0],
       [ 0,  0, 17, 18,  0]])

In [676]:
# МАТРИЧНЫЕ ОПЕРАЦИИ НАД МАССИВАМИ

In [677]:
av = np.arange(1, 5).reshape(-1, 2)
av

array([[1, 2],
       [3, 4]])

In [678]:
bv = np.array([[1, 2], [-2, 1]])
bv

array([[ 1,  2],
       [-2,  1]])

In [679]:
av*bv # поэлементное умножение

array([[ 1,  4],
       [-6,  4]])

In [680]:
np.matmul(av, bv) # умножение матриц

array([[-3,  4],
       [-5, 10]])

In [681]:
np.dot(av, bv) # скалярное умножение векторов

array([[-3,  4],
       [-5, 10]])

In [682]:
# без копирования

am = np.asmatrix(av)
bm = np.asmatrix(bv)

am, bm

(matrix([[1, 2],
         [3, 4]]),
 matrix([[ 1,  2],
         [-2,  1]]))

In [683]:
am * bm # матричное умножение

matrix([[-3,  4],
        [-5, 10]])

In [684]:
av**2 # поэлементное возведение в степень

array([[ 1,  4],
       [ 9, 16]])

In [685]:
am**2 # матричное возведение в степень

matrix([[ 7, 10],
        [15, 22]])

In [686]:
# ИНДЕКСАЦИЯ В ОДНОМЕРНЫХ МАССИВАХ

In [687]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [688]:
a[0], a[5], a[len(a)-1]

(0, 5, 14)

In [689]:
a[len(a)-1], a[-1]

(14, 14)

In [690]:
a[len(a)-5], a[-5]

(10, 10)

In [691]:
variants = [a[0:5:1], a[0:5], a[:5]]
print(*map(repr, variants), sep='\n')

array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])


In [692]:
variants = [a[0:len(a):2], a[0::2], a[::2]]
print(*map(repr, variants), sep='\n')

array([ 0,  2,  4,  6,  8, 10, 12, 14])
array([ 0,  2,  4,  6,  8, 10, 12, 14])
array([ 0,  2,  4,  6,  8, 10, 12, 14])


In [693]:
variants = [a[1:len(a):2], a[1::2]]
print(*map(repr, variants), sep='\n')

array([ 1,  3,  5,  7,  9, 11, 13])
array([ 1,  3,  5,  7,  9, 11, 13])


In [694]:
variants = [a[3:12:3], a[3:-3:3]]
print(*map(repr, variants), sep='\n')

array([3, 6, 9])
array([3, 6, 9])


In [695]:
variants = [a[3:13:3][::-1], a[12:2:-3], a[-3:2:-3]]
print(*map(repr, variants), sep='\n')

array([12,  9,  6,  3])
array([12,  9,  6,  3])
array([12,  9,  6,  3])


In [696]:
# БУЛЕВА ИНДЕКСАЦИЯ

In [697]:
np.random.seed(1234)

a = np.random.randint(-2, 7, 34)
a

array([ 1,  4,  3,  2,  6, -1,  5,  4,  6, -2,  3, -2,  4,  0, -2,  3,  0,
        4,  1,  5, -2, -2,  1,  0,  1, -1,  1, -1,  1,  5, -1,  5,  2, -2])

In [698]:
a<0

array([False, False, False, False, False,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False,  True])

In [699]:
a[a<0]

array([-1, -2, -2, -2, -2, -2, -1, -1, -1, -2])

In [700]:
variants = [a[a%3==0], a[np.logical_not(a%3)], a[~((a%3).astype(bool))]]
print(*map(repr, variants), sep='\n')

array([3, 6, 6, 3, 0, 3, 0, 0])
array([3, 6, 6, 3, 0, 3, 0, 0])
array([3, 6, 6, 3, 0, 3, 0, 0])


In [701]:
np.random.seed(1234)

a = np.random.randint(0, 9, 23)
a

array([3, 6, 5, 4, 8, 1, 7, 6, 8, 0, 5, 0, 6, 2, 0, 5, 2, 6, 3, 7, 0, 0,
       3])

In [702]:
mask3 = a % 3 == 0
mask5 = a % 5 == 0

variants = [a[np.logical_or(mask3, mask5)], a[mask3 | mask5]]
print(*map(repr, variants), sep='\n')

array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3])
array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3])


In [703]:
mask2 = a % 2 == 0
mask3 = a % 3 == 0

variants = [a[np.logical_and(mask2, mask3)], a[mask2 & mask3], a[a % 6 == 0]]
print(*map(repr, variants), sep='\n')

array([6, 6, 0, 0, 6, 0, 6, 0, 0])
array([6, 6, 0, 0, 6, 0, 6, 0, 0])
array([6, 6, 0, 0, 6, 0, 6, 0, 0])


In [704]:
# ИНДЕКСАЦИЯ В МНОГОМЕРНЫХ МАССИВАХ

In [705]:
a = np.arange(30).reshape(5, -1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [706]:
# не рекомендуется

a[0][0], a[0][2], a[1][1], a[-1][-2]

(0, 2, 7, 28)

In [707]:
# рекомендуется

a[0,0], a[0,2], a[1,1], a[-1,-2]

(0, 2, 7, 28)

In [708]:
variants = [a[2], a[2,:]]
print(*map(repr, variants), sep='\n')

array([12, 13, 14, 15, 16, 17])
array([12, 13, 14, 15, 16, 17])


In [709]:
a[:,3]

array([ 3,  9, 15, 21, 27])

In [710]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [711]:
a[0,1::2]

array([1, 3, 5])

In [712]:
# a[i,j]: i-нечет., j%3=2, индексация по строкам обратная

a[1::2, 2::3][::-1]

array([[20, 23],
       [ 8, 11]])

In [713]:
np.random.seed(2238)

a = np.random.randint(-5, 5, size=(5, 5))
a

array([[ 3,  2, -1, -3,  4],
       [ 3, -2, -2, -2, -5],
       [ 3,  2, -1,  1,  1],
       [ 2,  0,  4, -2,  0],
       [ 0,  4,  1,  2,  4]])

In [714]:
a[(a==0).any(axis=1)]

array([[ 2,  0,  4, -2,  0],
       [ 0,  4,  1,  2,  4]])

In [715]:
a[:, (a>0).sum(axis=0) > (a<0).sum(axis=0)]

array([[ 3,  2,  4],
       [ 3, -2, -5],
       [ 3,  2,  1],
       [ 2,  0,  0],
       [ 0,  4,  4]])

In [716]:
a[a>0]

array([3, 2, 4, 3, 3, 2, 1, 1, 2, 4, 4, 1, 2, 4])

In [717]:
np.where(a>0)

(array([0, 0, 0, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4]),
 array([0, 1, 4, 0, 0, 1, 3, 4, 0, 2, 1, 2, 3, 4]))

In [718]:
a[np.where(a>0)]

array([3, 2, 4, 3, 3, 2, 1, 1, 2, 4, 4, 1, 2, 4])

In [719]:
# FANCY INDEXING

In [720]:
a

array([[ 3,  2, -1, -3,  4],
       [ 3, -2, -2, -2, -5],
       [ 3,  2, -1,  1,  1],
       [ 2,  0,  4, -2,  0],
       [ 0,  4,  1,  2,  4]])

In [721]:
a[[2, 4, 3]] #2,3,4 строки

array([[ 3,  2, -1,  1,  1],
       [ 0,  4,  1,  2,  4],
       [ 2,  0,  4, -2,  0]])

In [722]:
a[[2, 4, 3]][:, [0, -1]] #2,3,4 строки и 1 и последний столбец (с копированием)

array([[3, 1],
       [0, 4],
       [2, 0]])

In [723]:
a[np.ix_([2,4,3],[0,-1])] # то же самое (без копирования)

array([[3, 1],
       [0, 4],
       [2, 0]])

In [724]:
# СОКРАЩЕННАЯ ИНДЕКСАЦИЯ

In [725]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [726]:
a[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [727]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [728]:
a[..., 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [729]:
# ГЕНЕРАЦИЯ СЛУЧАЙНЫХ ЧИСЕЛ

In [730]:
np.random.rand(10) # 10 случ. чисел от 0 до 1

array([0.22024735, 0.88293447, 0.69184538, 0.00523532, 0.48975893,
       0.78255915, 0.4244878 , 0.45827732, 0.0449126 , 0.5361042 ])

In [731]:
np.random.randint(0,10,10) # 10 случ. целых чисел от 0 до 10

array([8, 1, 5, 3, 8, 9, 7, 2, 1, 0])

In [732]:
np.random.permutation(10) # перестановка 10 чисел

array([6, 8, 5, 4, 9, 3, 1, 0, 2, 7])

In [733]:
np.random.choice(10, size=10) # выборка с повторениями 

array([4, 0, 2, 5, 7, 9, 3, 5, 4, 4])

In [734]:
# СОРТИРОВКА

In [735]:
np.random.seed(4445)

a = np.random.choice(10, size=(3,10))
a

array([[6, 0, 3, 1, 5, 3, 1, 6, 6, 4],
       [5, 3, 7, 1, 3, 0, 5, 5, 3, 6],
       [4, 1, 1, 0, 4, 3, 3, 3, 2, 1]])

In [736]:
np.sort(a.ravel()) # отсортированная копия

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 5,
       5, 5, 5, 6, 6, 6, 6, 7])

In [737]:
a.sort(axis=0) # сортировка по столбцам (без копии)
a

array([[4, 0, 1, 0, 3, 0, 1, 3, 2, 1],
       [5, 1, 3, 1, 4, 3, 3, 5, 3, 4],
       [6, 3, 7, 1, 5, 3, 5, 6, 6, 6]])

In [738]:
a.sort(axis=1) # сортировка по строкам
a

array([[0, 0, 0, 1, 1, 1, 2, 3, 3, 4],
       [1, 1, 3, 3, 3, 3, 4, 4, 5, 5],
       [1, 3, 3, 5, 5, 6, 6, 6, 6, 7]])

In [739]:
np.random.seed(4445)

a = np.random.choice(10, size=(3,10))
a

array([[6, 0, 3, 1, 5, 3, 1, 6, 6, 4],
       [5, 3, 7, 1, 3, 0, 5, 5, 3, 6],
       [4, 1, 1, 0, 4, 3, 3, 3, 2, 1]])

In [740]:
a.argsort(axis=0) # сортировка по индексам столбцов

array([[2, 0, 2, 2, 1, 1, 0, 2, 2, 2],
       [1, 2, 0, 0, 2, 0, 2, 1, 1, 0],
       [0, 1, 1, 1, 0, 2, 1, 0, 0, 1]])

In [741]:
a.argsort(axis=1) # сортировка по индексам строк

array([[1, 3, 6, 2, 5, 9, 4, 0, 7, 8],
       [5, 3, 1, 4, 8, 0, 6, 7, 9, 2],
       [3, 1, 2, 9, 8, 5, 6, 7, 0, 4]])

In [742]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [743]:
# ОБЪЕДИНЕНИЕ МАССИВОВ

In [744]:
from itertools import chain, zip_longest
def print_as_columns(*args, sep='\t'):
    args = list(map(lambda s: s.split('\n'), args))
    width = max(map(len, chain.from_iterable(args)))
    
    fill = lambda s: '{:<{width}s}'.format(s, width=width)
    fillvalue = fill('')
    
    args = map(lambda e: map(fill, e), args)
    args = map(sep.join, zip_longest(*args, fillvalue=fillvalue))
    print(*args, sep='\n')

In [745]:
np.random.seed(1398)

c = np.random.permutation(np.arange(0, 12))
i = c.shape[0] // 2

a, b = c[:i], c[i:]
a, b = a.reshape(3, 2), b.reshape(3, 2) 

In [746]:
print_as_columns(repr(a), repr(b))
np.vstack((a, b))

array([[8, 4],   	array([[ 1,  2], 
       [0, 3],   	       [11,  5], 
       [7, 6]])  	       [ 9, 10]])


array([[ 8,  4],
       [ 0,  3],
       [ 7,  6],
       [ 1,  2],
       [11,  5],
       [ 9, 10]])

In [747]:
np.concatenate((a, b), axis=0) # то же самое

array([[ 8,  4],
       [ 0,  3],
       [ 7,  6],
       [ 1,  2],
       [11,  5],
       [ 9, 10]])

In [748]:
print_as_columns(repr(a), repr(b))
np.hstack((a, b))

array([[8, 4],   	array([[ 1,  2], 
       [0, 3],   	       [11,  5], 
       [7, 6]])  	       [ 9, 10]])


array([[ 8,  4,  1,  2],
       [ 0,  3, 11,  5],
       [ 7,  6,  9, 10]])

In [749]:
np.concatenate((a, b), axis=1) # то же самое

array([[ 8,  4,  1,  2],
       [ 0,  3, 11,  5],
       [ 7,  6,  9, 10]])

In [750]:
# РАССТОЯНИЕ МЕЖДУ ТОЧКАМИ

In [751]:
from scipy.spatial.distance import pdist, squareform

np.random.seed(9872)
X = np.random.random(size=(5, 2))*10
X

array([[0.33823417, 2.08502959],
       [1.20627581, 5.15557834],
       [4.34896139, 2.34885034],
       [9.38091212, 0.89160899],
       [5.77386694, 4.41725834]])

In [752]:
d = pdist(X)
d

array([3.19088795, 4.01939476, 9.1210897 , 5.91484527, 4.21357267,
       9.219876  , 4.62687855, 5.23870982, 2.51170609, 5.04390507])

In [753]:
squareform(d)

array([[0.        , 3.19088795, 4.01939476, 9.1210897 , 5.91484527],
       [3.19088795, 0.        , 4.21357267, 9.219876  , 4.62687855],
       [4.01939476, 4.21357267, 0.        , 5.23870982, 2.51170609],
       [9.1210897 , 9.219876  , 5.23870982, 0.        , 5.04390507],
       [5.91484527, 4.62687855, 2.51170609, 5.04390507, 0.        ]])

In [754]:
norm = np.linalg.norm(X, ord=2, axis=1)
norm

array([2.11228567, 5.29481722, 4.9427283 , 9.42318836, 7.26978064])

In [755]:
squareform(pdist(X / norm[:, np.newaxis]))

array([[0.        , 0.06900716, 0.88320724, 1.22245132, 0.73897735],
       [0.06900716, 0.        , 0.82076742, 1.16710728, 0.67441346],
       [0.88320724, 0.82076742, 0.        , 0.39777586, 0.15768922],
       [1.22245132, 1.16710728, 0.39777586, 0.        , 0.55107649],
       [0.73897735, 0.67441346, 0.15768922, 0.55107649, 0.        ]])

In [756]:
pdist(X, metric='cosine')

array([0.00238099, 0.39002751, 0.74719361, 0.27304377, 0.33682958,
       0.6810697 , 0.22741676, 0.07911282, 0.01243295, 0.15184265])